[[plugins]]
  package = "@netlify/plugin-nextjs"
# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://cdn.jsdelivr.net/; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net/; img-src 'self' blob: data: https://i.ytimg.com/ https://img.youtube.com/; frame-src https://www.youtube.com/ https://www.google.com/ https://www.youtube-nocookie.com/ https://docs.google.com/ https://calendar.google.com/ https://*.google.com; font-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; upgrade-insecure-requests; block-all-mixed-content;"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-DNS-Prefetch-Control = "on"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
